### ISSUE TITLE
[Feature Request]: Systemd socket support.

### ISSUE THREAD

**Issue by vamega** [gershnik/wsdd-native#3]
This looks great, thanks for building this.

I was wondering if you'd consider adding systemd socket support to this project?
Right now wsdd-native requries permissions to bind to sockets, and by using `sd_listen_fds` it would be possible to set the unit up with [RestrictAddressFamilies=none](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RestrictAddressFamilies=).

Output in daemon mode is only sent to stdout, so I don't believe even AF_UNIX is necessary.

**Comment by vamega** [comment]
The launchd analog is [launch_activate_socket](https://developer.apple.com/documentation/xpc/1505523-launch_activate_socket).

I'm less familiar with launch, and don't know if this adds much value on Darwin.

**Comment by gershnik** [comment]
This is a very reasonable question to ask but, unfortunately, WS-Discovery protocol doesn't lend itself to this mode of operation. The WSD server isn't only serving TCP and UDP requests - it also must broadcast various messages over UDP and must bind to these sockets.

**Comment by vamega** [comment]
I believe that broadcasting on UDP is possible.

There is an option in [system.socket](https://www.freedesktop.org/software/systemd/man/systemd.socket.html#Broadcast=) that mentions it explicitly.

The docs also state

> No implicit WantedBy= or RequiredBy= dependency from the socket to the service is added. This means that the service may be started without the socket, in which case it must be able to open sockets by itself. To prevent this, an explicit Requires= dependency may be added.

This suggests that it's possible, although I'll admit I've never used systemd sockets with UDP multicast.

I'm happy to validate that hypothesis and get back to you if you'd be open to the feature if it's feasible.

**Comment by gershnik** [comment]
Hmmm. I am still not sure how this would work. My understanding is that the whole system.socket feature is meant for on-demand activation. What would activate the service in this case? If the service is activated independently and unconditionally what would it broadcast on if the sockets aren't available? If it is activated on-demand only then it cannot do "Hello" broadcasts on its own... Perhaps I am missing something though. 

In general taking sockets from outside _is_ feasible but there are quite a few complications. Currently wsddn operates like this:
1. It monitors existing interfaces and reacts when an interface is added or removed
2. It examines each interface for suitability and ignores it if it is not
3. It runs UDP multicast, unicast and TCP server on it.

This allows it to be installed with a simple system-independent service file and it automagically does the rest.

Now, it is theoretically possible to drive it all from outside. That is, have wsddn, given some command line flag, simply use sockets passed via `sd_listen_fds` and not do any detection of it own (beyond suitability checks).  BTW what happens if a new interface is added? Is the service restarted then or is it supposed to periodically check `sd_listen_fds` on its own?

So, if, somehow, it would be possible to fit the WS-Discovery protocol semantics into systemd driven sockets (including activation and adapting to interfaces added/deleted) then I don't have any objections to adding this functionality.

**Comment by gershnik** [comment]
Reading `sd_listen_fds` docs it simply reads things from the environment. That is the sockets are fixed once at service activation. Which means that using this mechanism you need new activation when interfaces are added. I don't see anything in the docs that implies this actually can be requested though....

**Comment by vamega** [comment]
Thanks for the information. I wasn't aware that wsdd-native did network interface monitoring. I don't think the the Python version did that.

What was the motivation behind adding network interface monitoring?
My use case doesn't really have network interfaces appearing/disappearing. It's a server with pretty well defined interfaces. Some physical, and perhaps I'd expose it over the tailscale interface as well.

It seems like a potential footgun when tools like docker can add virtual interfaces that `wsdd-native` might operate over, but I admit it's not something I've thought though.

> BTW what happens if a new interface is added? Is the service restarted then or is it supposed to periodically check sd_listen_fds on its own?

`sd_listen_fds` as you rightly point out cannot operate in any sort of pull model. The service would need to be restarted to get any new sockets.

**Comment by gershnik** [comment]
Python `wsdd` most definitely does that. 🙂 (See `class NetlinkAddressMonitor` in its sources for the Linux use case. I've committed some macOS patches to `wsdd` so I am quite familiar with its code).

The target use case for this is twofold. One is laptop and the other is wi-fi in general. Consider what happens when you bring your laptop to work. Even for a standalone "server" being connected over wi-fi which can come and go is not unheard of.
Also think of IoT devices that are almost always wi-fi only.

Docker is an interesting use case overall whether you monitor or not. There is IIRC a section on `wsdd` README page about how to deal with it. 

For either `wsdd` or `wsddn` you can force them to use only specific interfaces via command line switches, or for `wsddn` via `/etc/wsddn.conf`. 

Regardless, even assuming only fixed set of interfaces I still don't see how the activation flow would work. `systemd` will start the unit only when there is traffic on declared sockets, correct? But the daemon needs to broadcast on its own before any traffic is detected[1]. On the other hand if the unit is started unconditionally it can find that the socket isn't there yet. 
Unless I am missing some `systemd` feature it seems that what you propose isn't feasible.

[1] - Granted on a realistic network "eventually" a Windows host will multicast something so this might cause activation overall. But relying on this would be very hacky.

**Comment by gershnik** [comment]
Correct, in most setups the actual interface would always exist (though this isn't a given either, consider VPN and other things that toy with interface configuration). However from software point of view the distinction is not very important. When wi-fi connects you get a new address, your multicast address needs to change, IPv6 may be available or not etc. etc. From WS-Discovery implementation point of view it's a "new thing". 

Sure thing, if you manage to get activation working this would be a good feature to add and no rush.

**Comment by gershnik** [comment]
Is this still actionable? 🙂

**Comment by vamega** [comment]
No, I'll close this.
