### ISSUE TITLE
Somme question to compare with wsdd2

### ISSUE THREAD

**Issue by Nardol** [gershnik/wsdd-native#5]
Hello,

By reading https://github.com/Netgear/wsdd2 they specify:
> WSD/LLMNR Discovery/Name Service Daemon

It looks like it also supports LLMNR discovery.
Isn't it the case for WSDD-native?
And what about this Name service daemon? Is it only a client part?
Or do they only specify more words which are also part of this project?

I consider trying WSDD-native as it looks like WSDD2 try to read /proc/sys/dev/boot/info which does not exist and I am asking myself it it does not cause some issues.

In another topic, could it be planned to add what NMBD from Samba provides? Because in the case of KSMBD, it would add a missing piece which complete all except if I miss-understand something.

Thanks.

**Comment by gershnik** [comment]
Hi!

wsdd-native doesn't support LLMNR and there are no plans to do so.  
Note that per [Wikipedia](https://en.wikipedia.org/wiki/Link-Local_Multicast_Name_Resolution):
> As of April 2022, Microsoft has begun the process of phasing out both LLMNR and [NetBIOS](https://en.wikipedia.org/wiki/NetBIOS#Name_service) name resolution in favour of [mDNS](https://en.wikipedia.org/wiki/Multicast_DNS)

NetBIOS name resolution is what NMBD provides and this technology has been obsolete for a long time. You have to specially coax Windows to use it - it doesn't do it out of the box. 

Not sure what "name service daemon" in wsdd2 is exactly about - probably better to ask its developers. 

If you plan to use KSMBD then all you need is wsdd-native to have Windows show the shares in Explorer and, if you have Macs, [Avahi](https://avahi.org) to have Macs show the shares in Finder.

Note that wsdd-native (and last I checked, wsdd2) won't be able to detect KSMBD settings because both look for Samba config only to detect things like workgroup name and SMB host name. If you customize them you will need to also manually customize wsdd-native (via `/etc/wsddn.conf`). If you use defaults the things should "just work".

I do plan to eventually support reading KSMBD config but it will take some time to investigate how to do it cleanly.

Hope it helps and don't hesitate to ask for further help!

**Comment by Nardol** [comment]
Hi!

Thanks for your very quick reply :slightly_smiling_face:

> NetBIOS name resolution is what NMBD provides and this technology has been obsolete for a long time.

Yes but unfortunately, it looks VLC for Android (have not tested yet for other platforms) still relies on it, fortunately it also relies on MDNS but in my case, I set some favorites which point to the netbios name so I would have to reset these, that's why I asked for.
I have not had any answer on VLC official forum so it is only suspicions after some investigations on my setup.

But it looks I have not understood something about Netbios by reading your reply :wink: maybe VLC relies on something else, nobody looks having the answer... And except if I miss-configured WSDD2, LLMNR does not seem to be used by VLC.
I asked about it to be sure about what is provided or not by each solution. If LLMNR is not useful in my case I will use WSDD-Native.

Thanks for your help, so I was not wrong about everything for the setup with KSMBD.
For me setting by config file is not a problem, less a problem than understanding all these protocoles :laughing:

**Comment by gershnik** [comment]
As far as I understand about VLC (which is admittedly not very much) it uses Bonjour/mDNS to browse for available shares and services. If that is correct then all you need is Avahi. When properly configured it should expose your Linux machine SMB shares to be visible by VLC (and Macs for that matter). There are some samples of various quality on the web how to do it. There might be some trick ones in what specific services to expose to make it work. 

If that doesn't work I am not sure what the best approach would be other than asking VLC developers. It is possible that on Android it can't do mDNS or some such but who knows. 🙂

HTH

**Comment by Nardol** [comment]
Oops, I forgot "TV" after Android but I don't think it changes anything.
In fact with Samba I have my Linux server twice.
* First has address smb://ip_addr
* Last has smb://machine_name (without .local)

But without Samba I only have the first, which break some favorites.
I thought it was Netbios but is only suppositions.
Now I posted on the Videolan forum I only have to hop I will have some answer.

Thanks for your help, this last comment begins to be really off-topic about wsdd-native so I close this issue before it becomes too much off-topic... Except if you want it to stay opened for the KSMBD support.

Best regards.

**Comment by gershnik** [comment]
I'd check the Avahi config with/without Samba but yeah this would be better addressed on Avahi or VLC forums.
Closing this as I am tracking KSMBD support elsewhere.

Good luck!
