### ISSUE TITLE
wsdd-native advertising fine to Windows 10/11, not to Linux Mint

### ISSUE THREAD

**Issue by rtissera** [gershnik/wsdd-native#8]
wsdd-native does adverstise my embedded device fine to Windows 10/11 computers.
However on Linux Mint, I can't see the device, I have to manually connect to the device share.
Tested with 1.9 release built from source.

**Comment by gershnik** [comment]
Thank you for reporting this!
Can you check 
1. What is reported when you run `wsddn` interactively?
2. Do you have firewall enabled on this system? If so did you open the required ports as described [here][https://github.com/gershnik/wsdd-native?tab=readme-ov-file#firewall-setup]

FWIW I have tried both binary distribution and to build from sources on a Mint VM and it works fine so hopefully what you see is something due to some configuration issue.

**Comment by gershnik** [comment]
Wait, just realized something. Are you saying that you cannot see the embedded device **from** Linux Mint? If so, please disregard the above. wsddn-native cannot make _Linux_ see the device it is running on. It implements a protocol Windows and only Windows is using. 
If you want Mac or Linux to _also_ see the device too you need something else - usually mDNS server like Avahi
